version: '3'

services:

  admin_backend:
    container_name: admin-container
    image: admin-image
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/backend/Dockerfile
    networks:
      - admin_backend
    ports:
      - "8000:8000"

#  proxy:
#    build:
#      context: ./docker/proxy
#      restart: always
#      volumes:
#        - "/etc/letsencrypt:/etc/letsencrypt"
#        - "/var/lib/letsencrypt:/var/lib/letsencrypt"
#        - "static:/static"
#      ports:
#        - "80:80"
#        - "443:443"
#      depends_on:
#        - backend
#      networks:
#        - backend
#      environment:
#        - DOMAIN=${DOMAIN}