version: '3.9'

services:
  admin_backend:
    container_name: admin-container
    image: admin-image
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/admin/Dockerfile
    depends_on:
      - admin_db
    networks:
      - admin_backend
    ports:
      - "8000:8000"

  admin_db:
    container_name: admin-db
    image: postgres
    environment:
      POSTGRES_DB: olive_garden_admin  # Corrected the key from POSTGRES_DATABASE to POSTGRES_DB
      POSTGRES_USER: root  # Corrected the key from POSTGRES_USERNAME to POSTGRES_USER
      POSTGRES_PASSWORD: root # This remains the same
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    networks:
      - admin_backend


volumes:
  postgres:

networks:
  admin_backend: